branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/github'
    - - '@semantic-release/exec'
      - verifyConditionsCmd: "semantic-release-rust verify-conditions"
        prepareCmd: "semantic-release-rust prepare ${nextRelease.version}"
        publishCmd: "cargo make release && semantic-release-rust publish"
    - - '@semantic-release/changelog'
    - - '@semantic-release/git'
      - assets:
        - Cargo.toml
        - CHANGELOG.md
