on:
  push:
    branches: [staging, trying]

env:
  CARGO_TERM_COLOR: always

name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
          - stable

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make

      - name: Build and Lint
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: ci

      - name: Test
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.0'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - uses: ahmadnassri/action-commit-lint@v1
        with:
          config: conventional

  # This job should depend on all required jobs.
  # We will make Bors watch this job to tell whether to merge or not.
  done:
    name: Done
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo Done
